### ISSUE TITLE
Design the bridge between dashboard and notebook hubs

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-ui#321] opened 2022-11-11 15:36 UTC
Motivation:
We want someway for users to be able to go from exploring a dataset in the dashboard to exploring the dataset in the notebook hubs.

Current state:
- We have a dataset usage property and usage tab where we have started adding links
- We want some way of going from the explore page to the notebooks
- The SMCE dev team is also working on an API to take arbitrary code snippets and open them in the hub

Some ideas:
- "Open in Hub" feature of map explorer: I think we want a simple notebook or code snippet that works for most datasets about how to open and explore a dataset via the STAC API. This notebook or code snippet would be the default "explore/open in hub" notebook where the user can just swap out the collection id. _This could actually be how we use the API SMCE is working on - the code in the API call changes dependent on what dataset is currently being explored._
- More advanced notebooks can be linked to in the "usage tab" - both their static versions and links to the hub.

**Comment by michaelgsuttles** [comment] 2023-02-07 19:55
This appears to be a duplicate of #174 in veda-architecture. Closing.

**Closed by michaelgsuttles** 2023-02-07 19:55 UTC
