### ISSUE TITLE
Smoother access to production after recent deployment

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#386] opened 2022-12-13 23:39 UTC
## Description

Following a production push, there is usually a period of time where users have to clear their cache and experience other issues when accessing the site.

From Daniel:

> The CDN take some time to get updated and so it fails.
> In my case sometimes works, sometimes doesn’t, depending on which CDN my app comes from
> I don’t know if this CND cache can be flushed, but it’s something than would need to be done on MCP

This may take the form of working with MCP, but thought it would be useful to document in a ticket on our side.

**Comment by hanbyul-here** [comment] 2023-01-06 20:49
I recorded the weird behavior after the production deploy today. 


https://user-images.githubusercontent.com/4583806/211096897-30715b08-0697-492f-8e8f-346b48ac6b73.mov



When a user lands on the main page, it shows the old contents. But when a user navigates back to the landing page from one of the thematic areas, the landing page shows the newer content. (I think it is because Parcel loads the new js files on each route. It aligns with other CDN problems but I thought it would be worth recording the behavior.)

**Comment by slesaad** [comment] 2023-01-11 15:50
The auto cache invalidation has been added to the GitHub action to run on every production deployment. (see the attached merged PR)

I'll keep this issue open (in review) until we actually run a production deployment and see if it has solved the issue.

**Comment by Catalina-Moller** [comment] 2023-01-13 15:57
Currently we have not been able to reproduce the flow discussed by Hanbyul and have not seen any other issues arising from this problem. 

@slesaad Let me know if you want me to move the task to In Review, leave it in QA or where you would like it to be.

**Closed** 2023-01-20 20:46 UTC
