### ISSUE TITLE
[Refactor] Composite Features - Time-Series Analysis Tool (E&A)

### ISSUE THREAD

**Issue by sandrahoang686** [NASA-IMPACT/veda-ui#900] opened 2024-03-21 22:25 UTC
### Context

This tickets is to create a composite feature within veda-ui. Composite features are the core of VEDA and often combine different components to make a specialized tool for the dashboard. 

These are view containers that deliver a core part of the VEDA dashboard product and these containers are composed of resuseable components - so when breaking this out, think about pieces that can be reuseable and start to modularize the stateless/presentational components as well. 

**Notes:**
* Mark new files for VEDA2 refactor with `@VEDA2-REFACTOR-WORK`

**Acceptance Criteria:**
**General**
- [ ] Reusability => modularize stateless/presentational features to be as reuseable as possible within the core feature view containers
- [ ] Composite Feature should be entirely data agnostic => Separate out the data logic from this feature component into the data layer. _Note: Data will now have to be passed in as props so we will need to update the page views to supply this_
   - [ ] Composite Features should have stricter typed interfaces
- [ ] This feature should still support current instances and be backwards compatible

**Specific**
_{TO BE UPDATED}_

**Related to:** https://github.com/NASA-IMPACT/veda-ui/issues/801

**Resources:**
* ADR: https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/adr/002-application-architecture-for-configurability.md#decision-outcome
* [Miro Board outline Core Features](https://miro.com/app/board/uXjVNlIZVJI=/)

**Comment by aboydnw** [comment] 2024-08-29 19:47
Closing as duplicate of #902

**Closed** 2024-08-29 19:48 UTC
Labels: veda v2
