### ISSUE TITLE
Load colormaps from TiTiler to ensure tiles and legend agree

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#885] opened 2024-03-13 08:50 UTC
Currently, we have to configure both the TiTiler dynamic tiling parameters for a colormap and the stops for the legend component. In principle, the stops could be generated dynamically, ideally by TiTiler, since it receives the rendering specs and we need to make sure legend and tiles agree.

I added a comment to this existing TiTiler feature request:

- https://github.com/developmentseed/titiler/discussions/509

## Acceptance criteria

- [ ] Colormaps are loaded from TiTiler

**Comment by j08lue** [comment] 2024-03-21 09:29
TiTiler implemented a method to get the full color table (usually 255 stops), which should work fine for our purpose as well.

- https://github.com/developmentseed/titiler/pull/796

Btw, other projects I learned about have been loading colormaps from [D3](https://d3js.org/d3-scale-chromatic/sequential), where they were identical with TiTiler's.

**Comment by j08lue** [comment] 2024-05-29 10:49
The`/colormaps` endpoint (docs [here](https://developmentseed.org/titiler/endpoints/colormaps/)) does not seem to be added to the GHG Center and VEDA APIs yet.

- https://staging-raster.delta-backend.com/docs
- https://ghg.center/api/raster/docs

 Might need a ticket in `veda-backend`.

**Comment by slesaad** [comment] 2024-06-06 14:28
It can be a part of this - https://github.com/NASA-IMPACT/veda-backend/issues/364.

**Comment by j08lue** [comment] 2024-08-19 09:37
## Context and Problem Statement

A TiTiler UI wants to offer to the user a **curated** list of colormaps to choose from, with visual previews or the colormaps.


## Decision Drivers

1. Agreement between legend and rendered colors. Small differences could compromise the information people derive from the maps - possibly unnoticed. Larger differences break the user experience.
2. Ease of implementation and maintenance
3. Decent performance
4. Support for custom colormaps. TiTiler can have registered custom colormaps. For the GHG Center, for example, we have a custom colormap for the [EPA methane datasets](https://earth.gov/ghgcenter/exploration?datasets=%5B%7B%22id%22%3A%22total-methane%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%5D&taxonomy=%7B%7D&search=&date=2019-12-31T23%3A00%3A00.000Z) - included in the code [here](https://github.com/NASA-IMPACT/veda-backend/tree/develop/raster_api/runtime/src/cmap_data). However, it seems like [/colorMaps](https://openveda.cloud/api/raster/docs#/ColorMaps/getColorMaps) does not return it.


## Considered Options

1. Hard-code the colormaps (name, hex/rgb values) in the UI code, pass common name (e.g. viridis) to TiTiler
2. Hard-code the colormaps (hex/rgb values) in the UI code, pass hex codes to Titiler
3. Load the colormaps from D3 (they should, as rio-tiler's, be derived from Matplotlib and agree), pass common name
5. Load the list of colormaps from TiTIler's `/colorMaps` endpoint and fetch the hex codes one by one from `/colorMaps/{colorMapId}`

## Decision Outcome

Chosen option: "???", because ...

## Pros and Cons of the Options

### Option 1 - Hard-coded, pass name

1. Good, because: simple & flexible
2. Bad, because: Loads of extra code
3. Bad, because: Agreement between legend and rendered colors NOT guaranteed

### Option 2 - Hard-coded, pass values

1. Good, because: Agreement between legend and rendered colors guaranteed
2. Bad, because: Loads of extra code
3. Bad, because: More data gets passed
6. Bad, because: Not making use of TiTiler builtins or custom colormaps

### Option 3 - Load from D3, pass name

1. Good, because: No extra code
2. Bad, because: Agreement between legend and rendered colors NOT guaranteed (afaik there are no formal specifications for colormaps, only common practice - is that good enough?)
3. Bad, because: Need to hard-code any custom colormaps registered in TiTiler

### Option 4 - Load from TiTiler, pass name

1. Good, because: Agreement between legend and rendered colors guaranteed
2. Good, because: Custom colormaps registered in TiTiler are available (NOT at this point! Needs to be fixed.)
3. Good, because: No duplication of colormap specifications in the code or dependencies (D3)
4. Bad, because: Requires whitelisting of colormaps for curated list
5. Bad, because: Requires a request for each colormap to get the rgb/hex values or images for preview

**Comment by aboydnw** [comment] 2024-10-17 23:31
Duplicate of #994

**Closed by aboydnw** 2024-10-17 23:31 UTC
Labels: stac-integration
