### ISSUE TITLE
Scope out support for sub-daily time resolution in time series exploration

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#830] opened 2024-02-09 10:48 UTC
A few months back, we considered adding support for sub-daily data timestamps in our time series exploration interface, so users could browse the EMIT plume dataset with its higher resolution.

- https://github.com/NASA-IMPACT/veda-config-ghg/issues/31

We then decided that this particular dataset needed a dedicated interface anyways and tabled the goal to implement sub-daily time stamps in our generic exploration interfaces.

We should pick this up again, though, because there will be cases of datasets that require that the user can
1. See the exact time for the image, e.g. HLS
2. Browse data that has values at a sub-daily frequency, e.g. GPM and CYGNSS.

## Acceptance criteria

- [ ] Describe the needs for sub-daily data browsing more closely and list the changes that would be required

**Comment by aboydnw** [comment] 2024-10-17 23:30
Duplicate of #1050

**Closed by aboydnw** 2024-10-17 23:30 UTC
